# docker file used to build the teranode base build docker image.
# https://github.com/bitcoin-sv/teranode-base/blob/main/Dockerfile_build
FROM ubuntu:noble

ARG TARGETOS
ARG TARGETARCH
ARG GITHUB_SHA

# Install packages and install Golang
ARG GO_VERSION=1.25.1
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates build-essential gawk bison manpages-dev file curl gnupg wget software-properties-common && \
    wget https://go.dev/dl/go${GO_VERSION}.${TARGETOS}-${TARGETARCH}.tar.gz && \
    tar -C /usr/local -xzf go${GO_VERSION}.${TARGETOS}-${TARGETARCH}.tar.gz && \
    ln -s /usr/local/go/bin/go /usr/bin/go && \
    ln -s /usr/local/go/bin/gofmt /usr/bin/gofmt

# 18 is the latest LTS version of NodeJS
ENV NODE_MAJOR=18

# Add nodesource to apt sources and install nodejs
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list &&\
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN apt-get update && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
